# Generated by Django 5.2 on 2025-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_newsletter_teammember_trustedcompany_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for job applications', null=True),
        ),
    ]
