# Generated by Django 5.2 on 2025-04-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joblisting_application_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('application_rate', models.FloatField(default=0.0, help_text='Applications per view (%)')),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('interview_count', models.PositiveIntegerField(default=0)),
                ('hired_count', models.PositiveIntegerField(default=0)),
                ('avg_time_to_apply', models.DurationField(blank=True, help_text='Average time between view and application', null=True)),
                ('time_to_first_application', models.DurationField(blank=True, null=True)),
                ('applicant_locations', models.JSONField(blank=True, default=dict, help_text='Count of applicants by location')),
                ('save_count', models.PositiveIntegerField(default=0, help_text='Number of times job was saved')),
                ('click_through_rate', models.FloatField(default=0.0, help_text='Percentage of views that resulted in application page view')),
                ('referral_sources', models.JSONField(blank=True, default=dict, help_text='Count of views by referral source')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='jobs.joblisting')),
            ],
            options={
                'verbose_name': 'Job Analytics',
                'verbose_name_plural': 'Job Analytics',
            },
        ),
    ]
