# Generated by Django 5.2 on 2025-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanalytics',
            name='daily_applications',
            field=models.JSONField(blank=True, default=dict, help_text='Daily application counts'),
        ),
        migrations.AddField(
            model_name='jobanalytics',
            name='daily_views',
            field=models.JSONField(blank=True, default=dict, help_text='Daily view counts'),
        ),
    ]
