# Generated by Django 5.2 on 2025-04-25 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobanalytics_daily_applications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(choices=[(30, '30 Days'), (60, '60 Days'), (90, '90 Days'), (180, '6 Months'), (365, '1 Year')], default=30)),
                ('featured_job', models.BooleanField(default=False, help_text='Job will be featured in listings')),
                ('priority_placement', models.BooleanField(default=False, help_text='Job will appear at the top of search results')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Package',
                'verbose_name_plural': 'Job Packages',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='JobRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('old_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('new_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='jobs.joblisting')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='jobs.jobpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_renewals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Renewal',
                'verbose_name_plural': 'Job Renewals',
                'ordering': ['-created_at'],
            },
        ),
    ]
