# Generated by Django 5.2 on 2025-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_joblisting_has_been_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image for the testimonial', null=True, upload_to='testimonials/'),
        ),
    ]
