# Generated by Django 5.2 on 2025-04-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_company_industry_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company'),
        ),
    ]
