# Generated by Django 5.1.8 on 2025-04-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_legal_pages'),
        ('jobs', '0002_legalpage'),
        ('jobs', '0016_fix_joblisting_company_references'),
    ]

    operations = [
    ]
