# Generated by Django 5.1.8 on 2025-04-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_populate_legal_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobanalytics',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobanalytics',
            name='last_updated',
        ),
    ]
