# Generated by Django 5.2 on 2025-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_legalpage_content_alter_legalpage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last message sent', null=True),
        ),
    ]
