# Generated by Django 5.2 on 2025-04-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_jobapplication_last_message_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='page_type',
            field=models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('faq', 'FAQ'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
