# Generated by Django 5.2 on 2025-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_legalpage_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SearchFind', max_length=100)),
                ('site_logo', models.ImageField(blank=True, help_text='Site logo for emails and branding', null=True, upload_to='site_settings/')),
                ('site_favicon', models.ImageField(blank=True, help_text='Site favicon', null=True, upload_to='site_settings/')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary color in hex format (e.g. #3B82F6)', max_length=20)),
                ('secondary_color', models.CharField(default='#1E40AF', help_text='Secondary color in hex format (e.g. #1E40AF)', max_length=20)),
                ('contact_email', models.EmailField(default='contact@searchfind.com', max_length=254)),
                ('support_email', models.EmailField(default='support@searchfind.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
