# Generated by Django 5.2 on 2025-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('home', 'Home Page'), ('jobs', 'Jobs Page'), ('companies', 'Companies Page'), ('candidates', 'Candidates Page')], max_length=20, unique=True)),
                ('title', models.CharField(default='Find Your Dream Job', max_length=255)),
                ('subtitle', models.CharField(default='Search thousands of jobs from top companies', max_length=255)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the hero section (recommended size: 1920x600px)', null=True, upload_to='hero_images/')),
                ('mobile_background_image', models.ImageField(blank=True, help_text='Background image for the hero section on mobile (recommended size: 768x500px)', null=True, upload_to='hero_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
    ]
