# Generated by Django 5.2 on 2025-05-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_line1',
            field=models.CharField(blank=True, default='123 Main Street', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line2',
            field=models.CharField(blank=True, default='Suite 456', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.TextField(blank=True, default='Monday - Friday: 9:00 AM - 6:00 PM\nSaturday: 10:00 AM - 2:00 PM\nSunday: Closed', help_text='Business hours, one per line'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(blank=True, default='New York', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(blank=True, default='+1 (123) 456-7890', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(blank=True, default='10001', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='state',
            field=models.CharField(blank=True, default='NY', max_length=50),
        ),
    ]
