# Generated by Django 5.2 on 2025-05-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_fix_company_owner'),
        ('jobs', '0025_sitesettings_address_line1_and_more'),
    ]

    operations = [
    ]
