# Generated by Django 5.2 on 2025-04-25 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_fix_joblisting_company_references'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='applicant_tracking',
            field=models.BooleanField(default=False, help_text='Advanced applicant tracking system'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='career_path_planning',
            field=models.BooleanField(default=False, help_text='Career path planning and recommendations'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='interview_preparation',
            field=models.BooleanField(default=False, help_text='AI interview preparation and practice'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='salary_insights',
            field=models.BooleanField(default=False, help_text='Salary insights and negotiation tips'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_job_posts',
            field=models.BooleanField(default=False, help_text='Post unlimited job listings'),
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=255, null=True)),
                ('path_steps', models.JSONField(default=list)),
                ('skills_to_acquire', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('estimated_timeline', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('experience_level', models.CharField(max_length=100)),
                ('salary_range_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_range_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factors', models.JSONField(default=list)),
                ('negotiation_tips', models.JSONField(default=list)),
                ('industry_trends', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Insights',
                'verbose_name_plural': 'Salary Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_job_listings', models.PositiveIntegerField(default=0)),
                ('active_job_listings', models.PositiveIntegerField(default=0)),
                ('expired_job_listings', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('new_applications', models.PositiveIntegerField(default=0)),
                ('reviewed_applications', models.PositiveIntegerField(default=0)),
                ('shortlisted_applications', models.PositiveIntegerField(default=0)),
                ('rejected_applications', models.PositiveIntegerField(default=0)),
                ('job_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('average_time_on_page', models.FloatField(default=0)),
                ('view_to_application_rate', models.FloatField(default=0)),
                ('application_to_shortlist_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='jobs.company')),
            ],
            options={
                'verbose_name': 'Employer Analytics',
                'verbose_name_plural': 'Employer Analytics',
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_questions', models.JSONField(default=list)),
                ('behavioral_questions', models.JSONField(default=list)),
                ('company_questions', models.JSONField(default=list)),
                ('practice_answers', models.JSONField(default=dict)),
                ('feedback', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to='jobs.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Preparation',
                'verbose_name_plural': 'Interview Preparations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job_listing')},
            },
        ),
        migrations.CreateModel(
            name='JobListingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('applications', models.PositiveIntegerField(default=0)),
                ('qualified_applications', models.PositiveIntegerField(default=0)),
                ('average_time_on_page', models.FloatField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('view_to_application_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_analytics', to='jobs.joblisting')),
            ],
            options={
                'verbose_name': 'Job Listing Analytics',
                'verbose_name_plural': 'Job Listing Analytics',
                'ordering': ['-date'],
                'unique_together': {('job', 'date')},
            },
        ),
        migrations.CreateModel(
            name='JobSeekerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('new_applications', models.PositiveIntegerField(default=0)),
                ('viewed_applications', models.PositiveIntegerField(default=0)),
                ('shortlisted_applications', models.PositiveIntegerField(default=0)),
                ('rejected_applications', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('profile_completion', models.FloatField(default=0)),
                ('job_views', models.PositiveIntegerField(default=0)),
                ('saved_jobs', models.PositiveIntegerField(default=0)),
                ('average_job_match', models.FloatField(default=0)),
                ('high_match_jobs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker Analytics',
                'verbose_name_plural': 'Job Seeker Analytics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
