# Generated by Django 5.1.8 on 2025-04-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_applicant_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackconfig',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (Default)'), ('GHS', 'Ghanaian Cedi'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar (Requires USD account)')], default='NGN', max_length=3),
        ),
    ]
